# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: detect-private-key
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: mypy .
      language: system
      pass_filenames: false
      types: [python]

  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint .
      pass_filenames: false
      language: system
      types: [python]

  - repo: local
    hooks:
    - id: tests
      name: tests
      entry: python manage.py test
      pass_filenames: false
      language: system
      types: [python]

exclude: |
  ^(tests|migrations|__pycache__|.venv)/.*$
