name: Deploy Image

on:
  push:
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-north-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2

      - name: Configure Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 324037305789.dkr.ecr.eu-north-1.amazonaws.com

      - name: Extract Tag Name
        id: extract_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag: $TAG_NAME"
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t 324037305789.dkr.ecr.eu-north-1.amazonaws.com:latest \
            -t 324037305789.dkr.ecr.eu-north-1.amazonaws.com:${{ steps.extract_tag.outputs.tag_name }} .

      # Configure Kubernetes for AWS EKS
      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --region us-east-1 --name fiction-express

      # Deploy Application to EKS
      - name: Deploy to EKS
        run: |
          kubectl rollout deployment/backend

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '324037305789.dkr.ecr.eu-north-1.amazonaws.com:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Upload Image
        run: |
          docker push 324037305789.dkr.ecr.eu-north-1.amazonaws.com/fiction --all-tags

      - name: Deploy Kubernetes Image
        run: |
          kubectl rollout restart deployment/backend
